### ISSUE TITLE
Type inference could be more precise for exceptions

### ISSUE THREAD

**Issue by brazdil** [brazdil/dexter#13]
DexCodeAnalyzer does not infer that a thrown/caught object must be a Throwable, or even further analyze the potential throwing sites to narrow down the type of the register.

```
    :try_start
        div-int/lit16 v0, p1, 0x0
        return v0
    :try_end
    .catch Ljava/lang/ArithmeticException; {:try_start .. :try_end} :handler

    :handler
    move-exception v0
    invoke-virtual {v0}, Ljava/lang/Object;->hashCode()I
    move-result v0
    return v0
```

In the example above, the inferred type of `v0` after `:handler` is Object, even though it clearly must be an instance of ArithmeticException.

**Comment by xurubin** [comment]
Improved in 489e2f845bf60a7ab145bd02ed9d1efe7c1b2ea5
