### ISSUE TITLE
022-interface fails to run

### ISSUE THREAD

**Issue by xurubin** [brazdil/dexter#6]
Two problems are exposed by this unit test. You can see them by diff between the disassembled dex file and original.
1. The static field mWahoo is incorrectly set by the static initialiser.
   .field public static final mFloaty:F = 5.0f
   <.field public static final mWahoo:Ljava/lang/String;
   
   > .field public static final mWahoo:Ljava/lang/String; = 5.0f
2. Interface LIface2Sub1 is missing base interface Iface2, Cloneable.

**Comment by brazdil** [comment]
1. Yeah, sorry. Already fixed that a couple of hours ago in 6411bcdbca50152e2dc45499fd73c9dd9d0322b9
   Though now I'm getting something slightly weird when compiling a bigger app - number of static initializers does not match the number of fields. Need to have a better look at that.
2. Will look into it..

**Comment by brazdil** [comment]
1. Number of initializers handled correctly in 1fb512fb63d310101625c169ea5afd59ec3249fc
2. Fixed in 4edf2d21abc8a33bad425620d7afc3d4e89d86d0
